export default {
    DownStairsGameTitleText: "Pork Old Man - Downstairs",
    Play1PText: "Play 1P",
    Play2PText: "Play 2P",
    PlayOnlineText: "Play Online",
    SettingText: "Setting",
    PauseText: "Pause",
    ContinueText: "Continue",
    PauseHintText: "Press Space/ESC to Pause",
    StartText: "Start",
    GameOverText: "GameOver",
    ScoresText: "Scores",
    RankText: "Rank",
    LifeText: "Life",
    SimplePlayer1Text: "P1",
    SimplePlayer2Text: "P2",
    ControlText: "Control",
    FollowMeText: "Follow me : ",
    NoSupportMobileText: "Sorry, this game does not support mobile platform, please use your desktop browser to play."
};
